#!/usr/bin/env ansible-playbook
---
# Configuring a heat template for automatically scaling instances
# ansible-playbook -v -i `ir workspace inventory` configure_heat.yaml

- hosts: undercloud
  become: no
  name: Using the heat service for autoscaling
  tasks:
    - import_role:
        name: '../roles/telemetry_autoscaling'
        tasks_from: configure_heat

...
