#!/usr/bin/env ansible-playbook
---
# Creating the stack deployment for autoscaling
# ansible-playbook -v -i `ir workspace inventory` creating_stack.yaml

- hosts: undercloud
  become: no
  name: Creating the stack deployment for autoscaling
  vars:
  tasks:
    - include_role:
        name: '../roles/telemetry_autoscaling'
        tasks_from: creating_stack

...
