#!/usr/bin/env ansible-playbook
---
# Testing automatic scaling of instances
# ansible-playbook -v -i `ir workspace inventory` test_autoscaling.yaml

- hosts: undercloud
  become: no
  name: Test automatic scaling of instances
  vars:
  tasks:
    - import_role:
        name: '../roles/telemetry_autoscaling'
        tasks_from: test_autoscaling
...
