#!/usr/bin/env ansible-playbook
---
# Verify overcloud deployment
# ansible-playbook -v -i `ir workspace inventory` verify_autoscaling.yaml

- hosts: undercloud
  become: no
  name: Verifying the overcloud deployment for autoscaling
  vars:
  tasks:
    - import_role:
        name: '../roles/telemetry_autoscaling'
        tasks_from: verify_autoscaling
...
