#!/usr/bin/env ansible-playbook
---
# Verify overcloud deployment
# ansible-playbook -v -i `ir workspace inventory` verify_autoscaling.yaml

- hosts: undercloud
  become: no
  name: RHELOSP-178984 Verifying the overcloud deployment for autoscaling
  tasks:

    - name: test service API endpoint(metric) for autoscaling
      shell: |
        source ~/stackrc;
        openstack endpoint list --service metric;
      register: result
      failed_when: result.rc >= 1

    - name: test service API endpoint(alarm) for autoscaling
      shell: |
        source ~/stackrc;
        openstack endpoint list --service alarming;
      register: result
      failed_when: result.rc >= 1

    - name: test service API endpoint(heat) for autoscaling
      shell: |
        source ~/overcloudrc;
        openstack endpoint list --service orchestration;
      register: result
      failed_when: result.rc >= 1

    - name: Verify that the services are running on the overcloud
      shell: |
        source ~/overcloudrc;
        sudo podman ps --filter=name='heat|gnocchi|ceilometer|aodh';
      register: result
      failed_when: result.rc >= 1

    - name: Verify that the time-series database service is available
      shell: |
        source ~/overcloudrc;
        openstack metric status --fit-width;
      register: result
      failed_when: result.rc >= 1

    - name: Check if flavor "small" exists
      shell: |
        openstack flavor list -f value -c Name | grep '^small$'
      register: flavor_check
      failed_when: false  # Allow task to continue even if the flavor doesn't exist


    - name: Create "small" flavor if not exists
      shell: |
        openstack flavor create --ram 512 --vcpus 1 --disk 1 small
      when: flavor_check.stdout == ""
      register: flavor_creation
      failed_when: false  # Allow task to continue even if the flavor doesn't exist
...
